package ui

import (
	"github.com/charmbracelet/lipgloss"
)

// LoadingMsg represents a loading animation frame
type LoadingMsg struct {
	Frame int
}

// LLMResponseMsg represents a message from the LLM
type LLMResponseMsg struct {
	Content string
}

// Represents a command suggestion if the LLM returns one.
type CommandSuggestionMsg struct {
	Command string
	Reason  string
}

// SystemMessage represents a system-level message, typically used for conveying
// information or instructions from the system to the user. Unlike LLMResponseMsg,
// which contains responses generated by the language model, SystemMessage is used
// for non-interactive, system-generated content such as status updates or alerts.
type SystemMessage struct {
	Content string
}

// Styles for Menace CLI UI
// Includes "boxes" for chat and input area
var (
	SidebarStyle = lipgloss.NewStyle().
			Width(20).
			PaddingRight(1).
			Foreground(lipgloss.Color("15"))

	HeaderStyle = lipgloss.NewStyle().
			Bold(true).
			Foreground(lipgloss.Color("10")).
			MarginBottom(1)

	ChatStyle = lipgloss.NewStyle().
			Padding(1).
			Border(lipgloss.RoundedBorder()).
			BorderForeground(lipgloss.Color("12"))

	InputStyle = lipgloss.NewStyle().
			Foreground(lipgloss.Color("6")).
			Bold(true)

	UserStyle = lipgloss.NewStyle().
			Foreground(lipgloss.Color("2")).
			Bold(true)

	SystemStyle = lipgloss.NewStyle().
			Foreground(lipgloss.Color("#bd93f9")).
			Bold(true)

	LLMStyle = lipgloss.NewStyle().
			Foreground(lipgloss.Color("#8be9fd")).
			Italic(true).
			Bold(true)
	// Style for the block cursor in the input
	CursorStyle = lipgloss.NewStyle().Reverse(true)

	ButtonStyle = lipgloss.NewStyle().
			Padding(0, 2).
			Margin(0, 1).
			Foreground(lipgloss.Color("#f8f8f2")).
			Bold(true).
			Border(lipgloss.RoundedBorder()).
			BorderForeground(lipgloss.Color("#bd93f9"))

	ThinkingState = "thinking"
)
